partytree/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from partytree import upload
from . import views
from .import supervisor
from .import cashier


app_name = 'partytree'

urlpatterns = [
    path('manage_category/', supervisor.manage_category, name='manage_category'),
    path('create_category/', supervisor.create_category, name='create_category'),
    path('edit_category/<str:pk>/', supervisor.edit_category, name='edit_category'),
    path('manage_product/', supervisor.manage_product, name='manage_product'),
    path('create_product/', supervisor.create_product, name='create_product'),
    path('edit_product/<str:pk>/', supervisor.edit_product, name='edit_product'),

    path('create_restock/<str:pk>/', supervisor.create_restock, name='create_restock'),
    path('manage_restock/', supervisor.manage_restock, name='manage_restock'),

    path('create_damage/<str:pk>/', supervisor.create_damage, name='create_damage'),
    path('manage_damages/', supervisor.manage_damages, name='manage_damages'),
    path('approve_damage/<str:pk>/',
         supervisor.approve_damage, name='approve_damage'),
    path('cancel_damages/<str:pk>/',
         supervisor.cancel_damages, name='cancel_damages'),
    path('pending_damages',
         supervisor.pending_damages, name='pending_damages'),

    path('manage_inventory/', supervisor.manage_inventory, name='manage_inventory'),
    path('EditInventory/<str:pk>/', supervisor.EditInventory, name='EditInventory'),

    path('create_order/', cashier.create_order, name='create_order'),
   
    path('add_items_to_chart/<str:pk>?', cashier.add_items_to_chart,name='add_items_to_chart'),
  
    path('delete_item/<str:pk>/', cashier.deletes, name='delete_item'),
    path('cancel_order/<str:pk>/', cashier.cancel_order,name='cancel_order'),
    path('checkout/<str:pk>/', cashier.checkout, name='checkout'),
    path('momocheckout/<str:pk>/', cashier.momocheckout, name='momocheckout'),
    path('search_order', cashier.search_order,name='search_order'),

    path('checkout_print/<str:pk>/', cashier.checkout_print, name='checkout_print'),
    path('Vew_order/<str:pk>/', cashier.Vew_order, name='Vew_order'),
    path('close_order', cashier.close_order, name='close_order'),
    path('close', cashier.close, name='close'),
    path('manage_order', cashier.manage_order, name='manage_order'),


    path('makepayment/<str:pk>/', cashier.makepayment, name='makepayment'),
    path('momomakepayment/<str:pk>/', cashier.momomakepayment, name='momomakepayment'),

    path('closing_stock/', supervisor.closing_stock, name='closing_stock'),
    path('closed_stock/', supervisor.closed_stock, name='closed_stock'),

    path('uploads_products', upload.uploads_products,name='uploads_products'),
    path('restock_products', upload.restock_products,name='restock_products'),
    path('daily_sales', cashier.daily_sales,name='daily_sales'),

    path('populate_inventory', cashier.populate_inventory,name='populate_inventory'),
    path('run_to_zero',supervisor.run_to_zero,name='run_to_zero'),

    path('open_stock',supervisor.open_stock,name='open_stock'),
    path('pmanage_closingstock_summery',supervisor.pmanage_closingstock_summery,name='pmanage_closingstock_summery'),
]

salon/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .import supervisor
from .import cashier


app_name = 'salon'

urlpatterns = [
    path('manage_category/', supervisor.manage_category, name='manage_category'),
    path('create_category/', supervisor.create_category, name='create_category'),
    path('edit_category/<str:pk>/', supervisor.edit_category, name='edit_category'),
    path('manage_product/', supervisor.manage_product, name='manage_product'),
    path('create_product/', supervisor.create_product, name='create_product'),
    path('edit_product/<str:pk>/', supervisor.edit_product, name='edit_product'),

    path('create_customer/', cashier.create_customer, name='create_customer'),
    path('orderitems/', cashier.orderitems.as_view(), name='orderitems'),
    path('delete_item/<str:pk>/', cashier.deletes, name='delete_item'),
    path('checkout/', cashier.checkout, name='checkout'),
    path('checkout_print/<str:pk>/', cashier.checkout_print, name='checkout_print'),
    path('Vew_order/<str:pk>/', cashier.Vew_order, name='Vew_order'),
    path('close_order', cashier.close_order, name='close_order'),
    path('close', cashier.close, name='close'),
    path('manage_order', cashier.manage_order, name='manage_order'),
    path('makepayment/<str:pk>/', cashier.makepayment, name='makepayment'),

    path('create_restock/', supervisor.create_restock, name='create_restock'),
    path('approve_restock/<str:pk>/',
         supervisor.approve_restock, name='approve_restock'),
    path('cancel_restock/<str:pk>/',
         supervisor.cancel_restock, name='cancel_restock'),
    path('manage_restock/', supervisor.manage_restock, name='manage_restock'),

    path('manage_inventory/', supervisor.manage_inventory, name='manage_inventory'),
    path('EditInventory/<str:pk>/', supervisor.EditInventory, name='EditInventory'),
    path('closing_stock/', supervisor.closing_stock, name='closing_stock'),
    path('closed_stock/', supervisor.closed_stock, name='closed_stock'),

    path('pending_restock/', supervisor.pending_restock, name='pending_restock'),
    path('daily_sales/', supervisor.daily_sales, name='daily_sales'),
    path('taxation/', supervisor.taxation, name='taxation'),


]

school_management_system/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from school_management_system import settings
from django.conf.urls.static import static
from school import views
from bankapi import verify_student
from django.contrib.auth.decorators import login_required

from rest_framework import permissions
from drf_yasg.views import get_schema_view
# from rest_framework.schemas import get_schema_view
from drf_yasg import openapi
from django.views.generic import TemplateView

schema_view = get_schema_view(
    openapi.Info(
        title="MSAC API",
        default_version='v1',
        description="Welcome Mulan",
        terms_of_service="http://www.msac.edu.gh/about/",
        contact=openapi.Contact(email="terkpeh1990@gmail.com"),
        license=openapi.License(name="#"),
    ),
    public=False,
    permission_classes=(permissions.IsAuthenticated,),
)




urlpatterns = [
    # path('openapi', get_schema_view(
    #         title="Your Project",
    #         description="API for all things …",
    #         version="1.0.0"
    #     ), name='openapi-schema'),
    # path('swagger-ui/', TemplateView.as_view(
    #     template_name='swagger-ui.html',
    #     extra_context={'schema_url':'openapi-schema'}
    # ), name='swagger-ui'),
    re_path(r'^doc(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('doc/', schema_view.with_ui('swagger', cache_timeout=0),name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0),name='schema-redoc'),

    path('accounts/logout/', views.logout_request, name='django_registration_register'),


    path('docs',schema_view.as_view()),
    path('', views.login_view, name='log'),
    path('logouts', views.logout_request,name='logouts'),
    path('school/', include('school.urls', namespace='school')),
    path('shop/', include('bakery.urls', namespace='shop')),
    path('partytree/', include('partytree.urls', namespace='partytree')),
    path('salon/', include('salon.urls', namespace='salon')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),

    #bank Api
    path('students',verify_student.student.as_view()),
    path('payment',verify_student.payment.as_view()),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

partytree/models.py
from django.contrib.auth.models import AbstractUser, User
from django_resized import ResizedImageField
from django.db import models
from django.db.models import Count
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from django.contrib.sessions.models import Session
import datetime
from school.utils import incrementor

User = settings.AUTH_USER_MODEL


# Create your models here.
class Categorys(models.Model):
    name = models.CharField(max_length=50,unique=True)

    def __str__(self):
        return self.name


class Products(models.Model):
    id = models.CharField(max_length=2000, primary_key=True)
    name = models.CharField(max_length=250)
    code = models.CharField(max_length=2000,null=True, blank=True)
    category = models.ForeignKey(Categorys, on_delete=models.CASCADE)
    unit_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    images = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

    # def save(self, *args, **kwargs):

    #     if not self.id:
    #         number = incrementor()
    #         self.id = number()
    #         while Products.objects.filter(id=self.id).exists():
    #             self.id = number()
    #     super(Products, self).save(*args, **kwargs)


class Inventorys(models.Model):
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    instock = models.PositiveIntegerField(default=0)
    outgoing = models.PositiveIntegerField(default=0)
    unit_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    avialable_stock = models.PositiveIntegerField(default=0)
    avialable_stock_cost = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return self.product_id.name + " " + str(self.avialable_stock)

    def save(self, *args, **kwargs):
        self.avialable_stock = self.instock - self.outgoing
        self.avialable_stock_cost = self.avialable_stock * self.unit_price
        super(Inventorys, self).save(*args, **kwargs)


class Damagess(models.Model):
    acc = (
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Cancelled', 'Cancelled'),
    )
    damage_date = models.DateTimeField(auto_now_add=True)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    cause = models.CharField(max_length=255)
    cost = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    dastatus = models.CharField(
        max_length=10, choices=acc, null=True, blank=True)
    clear = models.BooleanField(default = False)
    # created = models.DateTimeField(auto_now_add=True)
    # created_by = models.ForeignKey('auth.User', on_delete=models.SET_NULL,related_name='dcreatedbys' ,blank=True, null=True,default=None)
    # modified = models.DateTimeField(auto_now=True)
    # modified_by = models.ForeignKey('auth.User', on_delete=models.SET_NULL, related_name='dmodifiedbys', blank=True, null=True, default=None)
    # history = HistoricalRecords()

    def __str__(self):
        return self.product_id.name + " " + str(self.quantity)

    def save(self, *args, **kwargs):
        # user = get_current_user()
        self.cost = self.product_id.unit_price * self.quantity
        # if user and not user.pk:
        #     user = None
        # if not self.pk:
        #     self.created_by = user
        # self.modified_by = user
        super(Damagess, self).save(*args, **kwargs)


class Closing_stockss(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    closing_stock = models.PositiveIntegerField(default=0)
    avialable_stock_cost = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    closing_stock_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.product.name + " " + str(self.avialable_stock)


class Inventory_recordss(models.Model):
    stat = (
        ('Incoming', 'Incoming'),
        ('Outgoing', 'Outgoing'),
    )

    transaction_date = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    unit_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    quantity = models.PositiveIntegerField(default=0)
    avialable_stock_cost = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    status = models.CharField(
        max_length=10, choices=stat, null=True, blank=True)

    def __str__(self):
        return self.product.name

    def save(self, *args, **kwargs):
        self.avialable_stock_cost = self.quantity * self.unit_price
        super(Inventory_recordss, self).save(*args, **kwargs)


class Customers(models.Model):
    id = models.CharField(max_length=2000, primary_key=True)
    name = models.CharField(max_length=250)
    phone = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):

        if not self.id:
            number = incrementor()
            self.id = "CUS" + str(number())
            while Customers.objects.filter(id=self.id).exists():
                self.id = "CUS" + str(number())
        super(Customers, self).save(*args, **kwargs)


class Daily_Session(models.Model):
    stat = (
        ('Open', 'Open'),
        ('Closed', 'Closed'),
    )
    session_date = models.DateField()
    status = models.CharField(max_length=10, choices=stat)


class Orders(models.Model):
    pay = (
        ('Part Payment', 'Part Payment'),
        ('Full Payment', 'Full Paument'),
        ('No Payment', 'No Payment'),
    )
    id = models.CharField(max_length=2000, primary_key=True)
    order_date = models.DateField(auto_now_add=True,null=True, blank=True)
    gross_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00,null=True, blank=True)
    vat = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    total_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    amount_paid = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    balance = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    payments = models.CharField(
        max_length=25, choices=pay, null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)

    daily_session = models.ForeignKey(
        Daily_Session, on_delete=models.DO_NOTHING, null=True, blank=True)
    money_paid = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    money_balance = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)

    class Meta:
        ordering = ('-order_date',)

    def __str__(self):
        return self.id



    def save(self, *args, **kwargs):
        if self.gross_price:
            self.total_price = float(self.gross_price)
        else:
            self.total_price = 0.00
        cc = self.total_price - float(self.amount_paid)
        if cc < 0.00:
            self.balance = 0.00
        else:
            self.balance =cc
        self.money_balance = float(self.amount_paid) - float(self.total_price)

        if self.total_price == self.amount_paid:
            self.payments = 'Full Payment'
        elif self.amount_paid > 0 and self.amount_paid < self.total_price:
            self.payments = 'Part Payment'
        else:
            self.payments = 'No Payment'


        if not self.id:
            number = incrementor()
            self.id = number()
            while Orders.objects.filter(id=self.id).exists():
                self.id = number()
        super(Orders, self).save(*args, **kwargs)


class Order_Detailss(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    unit_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    quantity = models.IntegerField()
    gross_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    order_id = models.ForeignKey(Orders, on_delete=models.CASCADE)

    def __str__(self):
        return self.product.name

    def save(self, *args, **kwargs):
        self.gross_price = self.unit_price * self.quantity
        super(Order_Detailss, self).save(*args, **kwargs)


class Invoice(models.Model):
    id = models.CharField(max_length=2000, primary_key=True)
    order_id = models.ForeignKey(Orders, on_delete=models.DO_NOTHING)
    total_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)

    def save(self, *args, **kwargs):
        if not self.id:
            number = incrementor()
            self.id = "INV" + str(number())
            while Invoice.objects.filter(id=self.id).exists():
                self.id = "INV" + str(number())
        super(Invoice, self).save(*args, **kwargs)


class Closing_Stock_summery(models.Model):

    close_date = models.DateField(auto_now_add=True, unique=True)
    stock = models.PositiveIntegerField(default=0)
    closing_stock_value = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return str(self.stock)

class Opening_Stock_summery(models.Model):

    close_date = models.DateField(auto_now_add=True, unique=True)
    stock = models.PositiveIntegerField(default=0)
    closing_stock_value = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return str(self.stock)

partytree/views.py
from django.shortcuts import render

# Create your views here.

templates/partytree/create_order_out.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content%}
<div class="row">
    <div class="col-6">
        <div class="content">
            <div class="container-fluid">
                <div class="card card-primary card-outline">
                    <div class="card-body">
                        <table class="table table-striped table-sm" id="my_friends">
                            <thead>
                                <tr>
                                    <th>Item</th>
                                    <th>Unit Price</th>
                                    <th>Qty</th>
                                    <th>Amount (GHC)</th>
                                    <th>Action</th>


                                </tr>
                            </thead>
                            <tbody>
                                {% for item in detail %}
                                <tr>
                                    <td>{{item.product.name}}</td>
                                    <td>{{item.unit_price}}</td>
                                    <td>{{item.quantity}}</td>
                                    <td>{{item.gross_price}}</td>
                                    <td>
                                        <a href="{% url 'partytree:delete_item' item.id %}">Remove</a>
                                    </td>

                                </tr>
                                {% endfor %}
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>

                                <tr>

                                    <td></td>
                                    <td></td>
                                    <td><b>Sub Total</b></td>
                                    <td><b>{{order.gross_price}}</b> </td>

                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td><b>VAT 4%</b></td>
                                    <td><b>{{vat}}</b></td>

                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td><b>Total</b></td>
                                    <td><b>{{total_sum}}</b></td>
                                </tr>

                            </tbody>
                        </table>
                        <div class="row">

                            {% if order.due_date %}
                            <div class="col ">
                                <a class="btn btn-primary mt-2" href="{% url 'partytree:Takeorderitems' %}">Check Cost</a>

                            </div>
                            {% else %}
                            <div class="col ">
                                <a class="btn btn-primary mt-2" href="{% url 'partytree:orderitems' %}">Check Cost</a>

                            </div>
                            {% endif %}




                            <div class="col ">
                                <a class="btn btn-danger mt-2 ml-2" href="{% url 'partytree:checkout' %}">Proceed To Check
                                    Out</a>

                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="content">
            <div class="container-fluid">
                <div class="card">
                    <form id="friend-form" method="post" novalidate>
                        {% csrf_token %}
                        <div class="card card-primary card-outline">
                            <div class="card-body">
                                <div class="form-group ">
                                    {% for hidden_field in form.hidden_fields %}
                                    {{ hidden_field }}
                                    {% endfor %}

                                    <div class=" col-md-4 mx-auto">
                                        {% if form.non_field_errors %}
                                        <div class="alert alert-danger" role="alert">
                                            {% for error in form.non_field_errors %}
                                            {{ error }}
                                            {% endfor %}
                                        </div>
                                        {% endif %}
                                    </div>

                                    <div class="row">
                                        <div class="form-group col">
                                            {{ form.product|as_crispy_field }}
                                        </div>
                                        <div class="form-group col">
                                            {{ form.quantity|as_crispy_field }}
                                        </div>
                                    </div>

                                    <div class="form-row">
                                        <div class="col text-center">
                                            <button class="btn btn-primary" value="Create Friend">Add To Chart</button>
                                        </div>

                                    </div>

                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script>
    /*
        On submiting the form, send the POST ajax
        request to server and after successfull submission
        display the object.
    */
    $("#friend-form").submit(function (e) {
        // preventing from page reload and default actions
        e.preventDefault();
        // serialize the data for sending the form data.
        var serializedData = $(this).serialize();
        // make POST ajax call
        $.ajax({
            type: 'POST',
            url: "{% url 'partytree:Takeorderitems' %}",
            data: serializedData,
            success: function (response) {
                // on successfull creating object
                // 1. clear the form.
                $("#friend-form").trigger('reset');
                // 2. focus to nickname input
                $("#id_name").focus();

                // display the newly friend to table.
                var instance = JSON.parse(response["instance"]);
                var fields = instance[0]["fields"];
                $("#my_friends tbody").prepend(
                    `<tr>
                   <td>${fields["product"] || ""}</td>
                   <td>${fields["unit_price"] || ""}</td>
                   <td>${fields["quantity"] || ""}</td>
                   <td>${fields["gross_price"] || ""}</td>
                   </tr>`

                )
            },
            error: function (response) {
                // alert the error if any error occured
                alert(response["responseJSON"]["error"]);
            }
        })
    });

</script>
{% endblock %}

templates/partytree/manage_category.html
{% extends "base.html" %}
{% block content%}

<div class="col-12">
    <div class="card card-primary card-outline ">
        <div class="card-body">
            <a class="btn btn-primary btn-sm mb-1" href="{% url 'partytree:create_category' %}">Create Category</a>
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="example2" class="table  table-striped table-hover" role="grid"
                            aria-describedby="example2_info">
                            <thead class="">
                                <tr role="row">

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Category Name</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="CSS grade: activate to sort column ascending">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cat in category %}
                                </tr>
                                <tr role="row" class="odd">
                                    <td>{{ cat.name }}</td>
                                    <td>
                                        <a class="btn btn-sm btn-primary"
                                            href="{% url 'partytree:edit_category' cat.id %}">Edit</a>
                                    </td>
                                </tr>

                                {% endfor %}

                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.card -->
</div>
{% endblock %}

templates/partytree/manage_product.html
{% extends "base.html" %}
{% block content%}

<div class="col-12">
    <div class="card card-primary card-outline ">
        <div class="card-body">
            {% for group in user.groups.all %} {% if group.name == 'principal' or group.name == 'manager'  %}
                <a class="btn btn-primary btn-sm mb-1" href="{% url 'partytree:create_product' %}">Create Product</a>
             {% endif %}
            {% endfor %}
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="example2" class="table  table-striped table-hover" role="grid"
                            aria-describedby="example2_info">
                            <thead class="">
                                <tr role="row">
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Product ID</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Product Name</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Product Category</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Unit Price</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="CSS grade: activate to sort column ascending">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for pro in product %}
                                </tr>
                                <tr role="row" class="odd">
                                    <td>{{ pro.id }}</td>
                                    <td>{{ pro.name}}</td>
                                    <td>{{ pro.category}}</td>
                                    <td>{{ pro.unit_price}}</td>

                                    <td>
                                        {% for group in user.groups.all %} {% if group.name == 'partytreecashier'  %}
                                            <a class="btn btn-sm btn-outline-danger"
                                            href="{% url 'partytree:create_damage' pro.id %}">Record Damage</a>
                                        {% elif group.name == 'principal'  or group.name == 'manager'  %}
                                            <a class="btn btn-sm btn-outline-primary"
                                                href="{% url 'partytree:edit_product' pro.id %}">Edit</a>
                                            <a class="btn btn-sm btn-outline-warning"
                                                href="{% url 'partytree:create_restock' pro.id %}">Restock</a>

                                        {% endif %}
                                        {% endfor %}


                                    </td>
                                </tr>

                                {% endfor %}

                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.card -->
</div>
{% endblock %}