accounts/urls.py
from unicodedata import name
from django.urls import path
from django.conf import settings

from accounts import receivables


from .import accounts
from .import sub_accounts
from .import general_ledger
from .import pv
from .import payerbles
from .import student_bill
from .import transfers
from .import account_dashboard
from .import fixed_assets



app_name = 'accounts'

urlpatterns = [
    path('manage_accounts',accounts.manage_accounts,name='manage_accounts'),
    path('edit_accounts/<str:pk>/',accounts.edit_accounts,name='edit_accounts'),


    path('sub_accounts/<str:pk>/',sub_accounts.sub_accounts,name='sub_accounts'),
    path('edit_sub_accounts/<str:pk>/',sub_accounts.edit_sub_accounts,name='edit_sub_accounts'),

    path('general_ledger',general_ledger.general_ledger,name='general_ledger'),


    path('general_ledger',general_ledger.general_ledger,name='general_ledger'),
    path('create_pv',pv.create_pv,name='create_pv'),
    path('pv_detail/<str:pk>/',pv.pv_detail,name='pv_detail'),

    path('deletes_pvitems/<str:pk>/',pv.deletes_pvitems,name='deletes_pvitems'),
    path('manage_pv',pv.manage_pv,name='manage_pv'),
    path('pending_pv',pv.pending_pv,name='pending_pv'),
    path('view_pv/<str:pk>/',pv.view_pv,name='view_pv'),
    path('cancelled/<str:pk>/',pv.cancelled,name='cancelled'),
    path('approve/<str:pk>/',pv.approve,name='approve'),

    path('manage_payables',payerbles.manage_payables,name='manage_payables'),
    path('make_payment/<str:pk>/',payerbles.make_payment,name='make_payment'),

    path('manage_receivables',receivables.manage_receivables,name='manage_receivables'),


    path('students',student_bill.students,name='students'),
    path('list_active_academic_terms/<str:pk>/',student_bill.list_active_academic_terms,name='list_active_academic_terms'),
    path('create_bill/<str:academicterm_id>/<str:student_id>/',student_bill.create_bill,name='create_bill'),
    path('student_bill_details/<str:pk>/',student_bill.student_bill_details,name='student_bill_details'),
    path('manage_bills',student_bill.manage_bills,name='manage_bills'),
    path('view_student_bill/<str:pk>/',student_bill.view_student_bill,name='view_student_bill'),
    path('run_student_bills',student_bill.run_student_bills,name='run_student_bills'),
    path('deletes_billitems/<str:pk>/',student_bill.deletes_billitems,name='deletes_billitems'),


    path('manage_transfer',transfers.manage_transfer,name='manage_transfer'),
    path('edit_transfer/<str:pk>/',transfers.edit_transfer,name='edit_transfer'),
    path('cancel_tranfer/<str:pk>/',transfers.cancel_tranfer,name='cancel_tranfer'),
    path('comfirm_tranfer/<str:pk>/',transfers.comfirm_tranfer,name='comfirm_tranfer'),
    path('account_dashboards',account_dashboard.account_dashboards,name='account_dashboards'),

    path('manage_assets',fixed_assets.manage_assets,name='manage_assets'),
    path('apply_discount/<str:pk>/',student_bill.apply_discount,name='apply_discount'),

    path('void_pv/<str:pk>/',pv.void_pv,name='void_pv'),
    path('parent_see_bill',student_bill.parent_see_bill,name='parent_see_bill'),

    path('receive_payment/<str:pk>/',receivables.receive_payment,name='receive_payment'),
    path('sales',receivables.sales,name='sales'),
    path('student_account/<str:pk>/',receivables.student_account,name='student_account'),
    path('view_individual_bill/<str:pk>/<str:rec>/',receivables.view_individual_bill,name='view_individual_bill'),




]

salon/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .import supervisor
from .import cashier


app_name = 'salon'

urlpatterns = [
    path('manage_category/', supervisor.manage_category, name='manage_category'),
    path('create_category/', supervisor.create_category, name='create_category'),
    path('edit_category/<str:pk>/', supervisor.edit_category, name='edit_category'),
    path('manage_product/', supervisor.manage_product, name='manage_product'),
    path('create_product/', supervisor.create_product, name='create_product'),
    path('edit_product/<str:pk>/', supervisor.edit_product, name='edit_product'),

    path('create_customer/', cashier.create_customer, name='create_customer'),
    path('orderitems/', cashier.orderitems.as_view(), name='orderitems'),
    path('delete_item/<str:pk>/', cashier.deletes, name='delete_item'),
    path('checkout/', cashier.checkout, name='checkout'),
    path('checkout_print/<str:pk>/', cashier.checkout_print, name='checkout_print'),
    path('Vew_order/<str:pk>/', cashier.Vew_order, name='Vew_order'),
    path('close_order', cashier.close_order, name='close_order'),
    path('close', cashier.close, name='close'),
    path('manage_order', cashier.manage_order, name='manage_order'),
    path('makepayment/<str:pk>/', cashier.makepayment, name='makepayment'),

    path('create_restock/', supervisor.create_restock, name='create_restock'),
    path('approve_restock/<str:pk>/',
         supervisor.approve_restock, name='approve_restock'),
    path('cancel_restock/<str:pk>/',
         supervisor.cancel_restock, name='cancel_restock'),
    path('manage_restock/', supervisor.manage_restock, name='manage_restock'),

    path('manage_inventory/', supervisor.manage_inventory, name='manage_inventory'),
    path('EditInventory/<str:pk>/', supervisor.EditInventory, name='EditInventory'),
    path('closing_stock/', supervisor.closing_stock, name='closing_stock'),
    path('closed_stock/', supervisor.closed_stock, name='closed_stock'),

    path('pending_restock/', supervisor.pending_restock, name='pending_restock'),
    path('daily_sales/', supervisor.daily_sales, name='daily_sales'),
    path('taxation/', supervisor.taxation, name='taxation'),


]

school_management_system/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from school_management_system import settings
from django.conf.urls.static import static
from school import views
from bankapi import verify_student
from django.contrib.auth.decorators import login_required

from rest_framework import permissions
from drf_yasg.views import get_schema_view
# from rest_framework.schemas import get_schema_view
from drf_yasg import openapi
from django.views.generic import TemplateView

schema_view = get_schema_view(
    openapi.Info(
        title="MSAC API",
        default_version='v1',
        description="Welcome Mulan",
        terms_of_service="http://www.msac.edu.gh/about/",
        contact=openapi.Contact(email="terkpeh1990@gmail.com"),
        license=openapi.License(name="#"),
    ),
    public=False,
    permission_classes=(permissions.IsAuthenticated,),
)




urlpatterns = [
    # path('openapi', get_schema_view(
    #         title="Your Project",
    #         description="API for all things …",
    #         version="1.0.0"
    #     ), name='openapi-schema'),
    # path('swagger-ui/', TemplateView.as_view(
    #     template_name='swagger-ui.html',
    #     extra_context={'schema_url':'openapi-schema'}
    # ), name='swagger-ui'),
    re_path(r'^doc(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('doc/', schema_view.with_ui('swagger', cache_timeout=0),name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0),name='schema-redoc'),

    path('accounts/logout/', views.logout_request, name='django_registration_register'),


    path('docs',schema_view.as_view()),
    path('', views.login_view, name='log'),
    path('logouts', views.logout_request,name='logouts'),
    path('school/', include('school.urls', namespace='school')),
    path('shop/', include('bakery.urls', namespace='shop')),
    path('partytree/', include('partytree.urls', namespace='partytree')),
    path('salon/', include('salon.urls', namespace='salon')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),

    #bank Api
    path('students',verify_student.student.as_view()),
    path('payment',verify_student.payment.as_view()),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.forms.widgets import NumberInput
# import datetime
from .import models



class DateInput(forms.DateInput):
    input_type = "date"


class AccountsForm(forms.ModelForm):

    class Meta:
        model = models.Accounts
        fields = '__all__'


class SubAccountsForm(forms.ModelForm):

    class Meta:
        model = models.Sub_Accounts
        fields = ('sub_code','sub_description','tag',)


class General_LedgerForm(forms.Form):

    transaction_date = forms.DateField(widget=NumberInput(attrs={'type': 'date'}), label='Date')
    description= forms.CharField(label='Description')
    debt_amount = forms.DecimalField(max_digits=10, decimal_places=2,label='Amount')
    credit_amount = forms.DecimalField(max_digits=10, decimal_places=2,label='Amount')


class PvForm(forms.ModelForm):
    ob = [4000,4120,4500,4700,4900,5000,5200,3020,4950,5100,5940,4600,5960,1000,11000]
    transaction_date = forms.DateField(widget=NumberInput(attrs={'type': 'date'}))
    sub_account = forms.ModelChoiceField(
         queryset=models.Sub_Accounts.objects.filter(code__code__in=ob).order_by('sub_description'))

    class Meta:
        model = models.Payment_Vouchers
        fields = ('transaction_date','sub_account','company','description')

class Pv_detailsForm(forms.ModelForm):
    description = forms.CharField(label=False)
    amount = forms.CharField(label=False)
    class Meta:
        model = models.APv_details
        fields = ('description','amount',)


class paymentform(forms.Form):
    ob = [1103,1200]
    amount_paid = forms.DecimalField(decimal_places=2,label='Amount')


class Student_Bill_Detail_Form(forms.ModelForm):
    description = forms.CharField(label=False)
    amount = forms.CharField(label=False)
    class Meta:
        model = models.Student_Bill_Details
        fields = ('description','amount',)


class transferform(forms.ModelForm):
    ob = [1103,1200,2154]
    transaction_date = forms.DateField(widget=NumberInput(attrs={'type': 'date'}))
    fromaccount_code = forms.ModelChoiceField(
         queryset=models.Sub_Accounts.objects.filter(code__code__in=ob).order_by('sub_description'), label='From')
    toaccount_code = forms.ModelChoiceField(
         queryset=models.Sub_Accounts.objects.filter(code__code__in=ob).order_by('sub_description'), label='To')
    tran_dec = forms.CharField(label='Transfer Description')

    class Meta:
        model = models.Transfers
        fields = ('transaction_date','fromaccount_code','tran_dec','toaccount_code','amount')

class Assetsform(forms.ModelForm):

    assets = forms.ModelChoiceField(
         queryset=models.Sub_Accounts.objects.filter(code__code=1000).order_by('sub_description'), label='Assets')

    class Meta:
        model = models.FixedAssets
        fields = ('assets','value','depreciation_rate')

class Discountform(forms.Form):

    discount = forms.DecimalField(decimal_places=2,label='Discount (%)')

    def clean(self, *args, **kwargs):
        discount = self.cleaned_data.get('discount')
        if discount:

            if discount <= 0:
                raise forms.ValidationError(
                    {'discount': ["Discount cannot be less than or equal to 0 "]})
            elif discount > 15:
                raise forms.ValidationError(
                    {'discount': ["Discount cannot be greater than 15% "]})

        return super(Discountform, self).clean(*args, **kwargs)

accounts/views.py
from django.shortcuts import render

# Create your views here.

templates/accounts/edit_transfer.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block content %}
<div class="row">
    <div class="col-lg">

        <div class="card  card-dark card-outline p-4 m-4">
            <h5>Transfers</h5>

            <div class="card-body">
                <form id="friend-form" role="form" method="POST" enctype="multipart/form-data" >
                    {% csrf_token %}
                    <div class="row">
                        <div class="form-group  col-12 col-md-4">
                            {{ form.transaction_date|as_crispy_field }}
                        </div>
                        <div class="form-group  col-12 col-md-8">
                            {{ form.tran_dec|as_crispy_field }}
                        </div>

                    </div>
                    <div class="row mb-3" >
                        <div class="col-12 col-md-5"style="border:solid #777271 2px;">

                            <div class="row">
                                <div class="col-12 col-md-12" style=" border-bottom : solid #777271 2px; text-align: center; margin-bottom: 20px;">
                                    <h5 class='ml-2'>Transfer From</h5>
                                </div>


                            </div>
                            <div class="row">

                                <div class="form-group  col-12 col-md-12">
                                    {{ form.fromaccount_code|as_crispy_field }}
                                </div>

                            </div>



                        </div>
                        <div class="col-12 col-md-5" style="border:solid #777271 2px; border-left: none;">
                            <div class="row">
                                <div class="col-12 col-md-12 " style=" border-bottom : solid #777271 2px; text-align: center; margin-bottom: 20px;">
                                    <h5 class='ml-2' >Transfer To</h5>
                                </div>


                            </div>
                            <div class="row">
                                <div class="form-group  col-12 col-md-12">
                                    {{ form.toaccount_code|as_crispy_field }}
                                </div>

                            </div>






                        </div>
                        <div class="col-12 col-md-2" style="border:solid #777271 2px; border-left: none;">
                            <div class="row">
                                <div class="col-12 col-md-12 " style=" border-bottom : solid #777271 2px; text-align: center; margin-bottom: 20px;">
                                    <h5 class='ml-2' >Amount</h5>
                                </div>


                            </div>
                            <div class="row">
                                <div class="form-group  col-12 col-md-12">
                                    {{ form.amount|as_crispy_field }}
                                </div>

                            </div>






                        </div>


                    </div>
                    <div class="make-request ml-2 ">
                        <button class="btn btn-dark">
                            <span class="pl-2">Update</span>
                            <i class="fas fa-plus pl-2"></i>
                        </button>

                    </div>
                    <br>
                <h5>Transactions </h5>
                </form>

                <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="example3" class="table  table-striped table-hover" role="grid"
                                aria-describedby="example2_info">
                                <thead class="">
                                    <tr role="row">
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending">ID</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending">Date</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending">Description</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending">From</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending">To</th>

                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending">Amount</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending">Status</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending">Action</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    {% for a in payables %}
                                    </tr>
                                    <tr role="row" class="odd">
                                        <td>{{ a.id }}</td>
                                        <td>{{ a.transaction_date}}</td>
                                        <td>{{ a.tran_dec}}</td>
                                        <td>{{a.fromaccount_code.sub_code }} -- {{a.fromaccount_code.sub_description}}</td>
                                        <td>{{a.toaccount_code.sub_code }} -- {{a.toaccount_code.sub_description}}</td>
                                        <td>{{a.amount }}</td>
                                        {% if a.status == "Pending" %}
                                            <td><span class="badge badge-pill badge-warning">{{ a.status }}</span></td>
                                        {% elif a.status == "Comfirmed" %}
                                            <td><span class="badge badge-pill badge-info">{{ a.status }}</span></td>
                                        {% else %}
                                            <td><span class="badge badge-pill badge-danger">{{ a.status }}</span></td>
                                        {% endif %}
                                        <td>
                                            {% for group in user.groups.all %}
                                            {% if group.name == 'principal' or group.name == 'account' %}
                                                {% if a.status == 'Pending' or a.status == 'pending' %}
                                                    <a class="btn btn-sm  btn-outline-warning" href="{% url 'accounts:edit_transfer' a.id %}">Edit</a>
                                                    <a class="btn btn-sm  btn-outline-primary" href="{% url 'accounts:comfirm_tranfer' a.id %}">Comfirm</a>
                                                    <a class="btn btn-sm  btn-outline-danger ml-4" href="{% url 'accounts:cancel_tranfer' a.id %}">Cancel</a>
                                                {% else %}

                                            {% endif %}
                                            {% endif %}

                                        {% endfor %}
                                        </td>

                                    </tr>

                                    {% endfor %}

                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/accounts/list_students.html
{% extends "base.html" %}
{% block content%}

<div class="col-lg">
    <div class="card card-dark card-outline">
        <div class="card-body">
           
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="example2" class="table table-bordered table-striped table-hover" role="grid"
                            aria-describedby="example2_info">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1"
                                        colspan="1" aria-sort="ascending"
                                        aria-label="Rendering engine: activate to sort column descending">ID
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Name</th>

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Platform(s): activate to sort column ascending">Gender</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Platform(s): activate to sort column ascending">DoB</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Engine version: activate to sort column ascending">Class
                                    </th>

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="CSS grade: activate to sort column ascending">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for student in students %}
                                </tr>
                                <tr role="row" class="odd">
                                    <td class="sorting_1">{{student.id}}</td>
                                    <td>{{ student.Surname }} {{ student.firstname }}</td>
                                    <td>{{student.gender}}</td>
                                    <td>{{student.dob}}</td>
                                    <td>{{student.course_id}}</td>
                                    <td>
                                        
                                        <a class="btn btn-sm btn-outline-dark"
                                        href="{% url 'accounts:list_active_academic_terms' student.id %}">Create Bill</a>
                                    </td>
                                </tr>

                                {% endfor %}

                            </tbody>
                            <tfoot>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.card -->
</div>
{% endblock %}

templates/accounts/student_account.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content%}

<div class='row'>
    <div class='col-12 col-md-12'>
        <div class="card card-dark card-outline  m-4">
        <div class="card-body">
            <h3 class="profile-username text-center text-muted">MULAN SMART ACTIVITY CENTER</h3>
            <ul class="list-group list-group-unbordered mb-3">
                <li class="list-group-item">
                    <b>Date</b> <a class="float-right text-muted">{{payables.transaction_date}}</a>
                </li>
                <li class="list-group-item">
                    <b>ID.</b> <a class="float-right text-muted">{{payables.id}}</a>
                </li>
                <li class="list-group-item">
                    <b>Description</b> <a class="float-right text-muted">{{payables.description}}</a>
                </li>

                <li class="list-group-item">
                    <b>Sub Code</b> <a class="float-right text-muted">{{payables.sub_code.sub_code }} -- {{payables.sub_code.sub_description}}</a>
                </li>

                <li class="list-group-item">
                    <b>Receivable Balance</b> <a class="float-right text-muted">{{payables.amount}}</a>
                </li>
            </ul>

               <a class="btn btn-md  btn-outline-danger " href="{% url 'accounts:receive_payment' payables.id %}">Make Payment</a>

               <a class="btn btn-md  btn-outline-primary  ml-4" href="{% url 'accounts:manage_receivables'  %}">Close</a>





        </div>

    </div><!-- /.card -->

    </div>
</div>
 <div class="row mb-3 ml-3 mr-3" >

          <div class="col-12 col-md-6 "style="border:solid #777271 2px;">

            <div class="row">
                <div class="col-12 col-md-12" style=" border-bottom : solid #777271 2px; text-align: center; margin-bottom: 20px;">
                    <h5 class='ml-2'>All Bills Generated</h5>
                </div>


            </div>
            <div class="row m-3">
                <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">

                        <div class="col-12 col-sm-12 col-md-12">

                            <table id="example2" class="table  table-hover" role="grid"
                                aria-describedby="example2_info">
                                <thead class="">
                                    <tr role="row">
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending">ID</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending">Date</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending">Period</th>
                                        <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending">Amount</th>




                                    </tr>
                                </thead>
                                <tbody>
                                    {% for a in bills %}

                                     <tr role="row" class="odd">

                                         <td><a href="{% url 'accounts:view_individual_bill' a.id payables.id %}">
                                             {{a.id}}
                                             </a>
                                         </td>
                                        <td><a href="{% url 'accounts:view_individual_bill' a.id payables.id %}">
                                            {{a.bill_date}}
                                            </a>
                                        </td>
                                        <td><a href="{% url 'accounts:view_individual_bill' a.id payables.id %}">
                                            {{a.term_year_id }}
                                            </a>
                                        </td>
                                        <td> <a href="{% url 'accounts:view_individual_bill' a.id payables.id %}">
                                            {{a.amount }}
                                            </a>
                                            </td>


                                    </tr>


                                    {% endfor %}

                                </tbody>

                            </table>
                        </div>

                    </div>
                </div>

            </div>



        </div>
        <div class="col-12 col-md-6" style="border:solid #777271 2px; border-left: none;">
            <div class="row">
                <div class="col-12 col-md-12 " style=" border-bottom : solid #777271 2px; text-align: center; margin-bottom: 20px;">
                    <h5 class='ml-2' >All Payment Transactions</h5>
                </div>


            </div>
            <div class="row m-3">
                <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
            <div class="row">

                <div class="col-12 col-sm-12 col-md-12">

                    <table id="example1" class="table  table-hover" role="grid"
                        aria-describedby="example2_info">
                        <thead class="">
                            <tr role="row">
                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                    aria-label="Browser: activate to sort column ascending">Payment ID</th>
                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                    aria-label="Browser: activate to sort column ascending">Payment Date</th>
                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                    aria-label="Browser: activate to sort column ascending">Amount Paid</th>
                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                    aria-label="Browser: activate to sort column ascending">Balance</th>


                            </tr>
                        </thead>
                        <tbody>
                            {% for a in his %}
                            </tr>
                            <tr role="row" class="odd">
                                <td>{{a.id}}</td>
                                <td>{{a.transaction_date}}</td>
                                <td>{{a.amount }}</td>
                                <td>{{a.balance }}</td>


                            </tr>

                            {% endfor %}

                        </tbody>

                    </table>
                </div>

            </div>
</div>
            </div>






        </div>




</div>

<!--<div class="col-12">-->


<!--</div>-->
{% endblock %}