salon/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .import supervisor
from .import cashier


app_name = 'salon'

urlpatterns = [
    path('manage_category/', supervisor.manage_category, name='manage_category'),
    path('create_category/', supervisor.create_category, name='create_category'),
    path('edit_category/<str:pk>/', supervisor.edit_category, name='edit_category'),
    path('manage_product/', supervisor.manage_product, name='manage_product'),
    path('create_product/', supervisor.create_product, name='create_product'),
    path('edit_product/<str:pk>/', supervisor.edit_product, name='edit_product'),

    path('create_customer/', cashier.create_customer, name='create_customer'),
    path('orderitems/', cashier.orderitems.as_view(), name='orderitems'),
    path('delete_item/<str:pk>/', cashier.deletes, name='delete_item'),
    path('checkout/', cashier.checkout, name='checkout'),
    path('checkout_print/<str:pk>/', cashier.checkout_print, name='checkout_print'),
    path('Vew_order/<str:pk>/', cashier.Vew_order, name='Vew_order'),
    path('close_order', cashier.close_order, name='close_order'),
    path('close', cashier.close, name='close'),
    path('manage_order', cashier.manage_order, name='manage_order'),
    path('makepayment/<str:pk>/', cashier.makepayment, name='makepayment'),

    path('create_restock/', supervisor.create_restock, name='create_restock'),
    path('approve_restock/<str:pk>/',
         supervisor.approve_restock, name='approve_restock'),
    path('cancel_restock/<str:pk>/',
         supervisor.cancel_restock, name='cancel_restock'),
    path('manage_restock/', supervisor.manage_restock, name='manage_restock'),

    path('manage_inventory/', supervisor.manage_inventory, name='manage_inventory'),
    path('EditInventory/<str:pk>/', supervisor.EditInventory, name='EditInventory'),
    path('closing_stock/', supervisor.closing_stock, name='closing_stock'),
    path('closed_stock/', supervisor.closed_stock, name='closed_stock'),

    path('pending_restock/', supervisor.pending_restock, name='pending_restock'),
    path('daily_sales/', supervisor.daily_sales, name='daily_sales'),
    path('taxation/', supervisor.taxation, name='taxation'),


]

school/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .import management
from .import staff
from .import principal
from .import accounting
from .import parent
from .import billing
from .import hostbill
from .import shop_manager
from .import sysadmin
from .import academic_year
from .import attendance
from .import assign_classes
from .import students
from .import subjects
from .import progress_report
from .import sms

app_name = 'school'

urlpatterns = [
path('add_student/<str:pk>/', students.add_student, name='add_student'),
    path('add_student_education_history/<str:pk>/', students.add_student_education,name='add_student_education_history'),
    path('remove_student_education/<str:pk>/', students.remove_student_education, name='remove_student_education'),
    path('add_student_emmergency_contact/<str:pk>/', students.add_student_emergency,name='add_student_emmergency_contact'),
    path('remove_student_emmergency_contact/<str:pk>/',students.remove_student_emmergency_contact,name='remove_student_emmergency_contact'),
    path('add_student_medical/<str:pk>/', students.add_student_medical,name='add_student_medical'),
    path('remove_student_medical/<str:pk>/',students.remove_student_medical,name='remove_student_medical'),
    path('add_student_immunization/<str:pk>/', students.add_student_immunization, name='add_student_immunization'),
    path('remove_student_immunization/<str:pk>/',students.remove_student_immunization,name='remove_student_immunization'),


    path('delete_student/<str:pk>/', students.delete_student, name='delete_student'),
    path('student_profile/<str:pk>/',students.student_profile, name='student_profile'),
    path('edit_student/<str:pk>/',students.edit_student, name='edit_student'),
    path('activate_status/<str:pk>/',students.activate_status, name='activate_status'),
    path('deactivate_status/<str:pk>/',students.deactivate_status, name='deactivate_status'),


    path('edit_student_edu/<str:pk>/', students.edit_student_education, name='edit_student_edu'),
    path('edit_student_emmergency/<str:pk>/',students.edit_student_emmergency, name='edit_student_emmergency'),
    path('edit_student_medical/<str:pk>/',students.edit_student_medical, name='edit_student_medical'),
    path('edit_student_immunization/<str:pk>/',students.edit_student_immunization, name='edit_student_immunization'),

    path('delete_student_education/<str:pk>/',students.delete_student_education, name='delete_student_education'),
    path('delete_student_emmergency/<str:pk>/',students.delete_student_emmergency, name='delete_student_emmergency'),
    path('delete_student_medical/<str:pk>/',students.delete_student_medical, name='delete_student_medical'),
    path('delete_student_immunization/<str:pk>/',students.delete_student_immunization,         name='delete_student_immunization'),

    path('add_profile_student_education/<str:pk>/',students.add_profile_student_education, name='add_profile_student_education'),
    path('add_profile_student_emmergency/<str:pk>/',
         students.add_profile_student_emmergency, name='add_profile_student_emmergency'),
    path('add_profile_student_medical/<str:pk>/',
         students.add_profile_student_medical, name='add_profile_student_medical'),
    path('add_profile_student_immunization/<str:pk>/',
         students.add_profile_student_immunization, name='add_profile_student_immunization'),

    path('manage_student', students.manage_student, name='manage_student'),

    path('assign_student_class/<str:pk>/',assign_classes.assign_student_class,name='assign_student_class'),
    path('run_class',assign_classes.run_class,name='run_class'),


    path('add_staff', management.add_staff, name='add_staff'),
    path('add_staff_education_history/<str:pk>/', management.add_staff_education,name='add_staff_education_history'),
    path('remove_edu_history/<str:pk>/', management.remove_edu_history,name='remove_edu_history'),

    path('add_staff_work_experience/<str:pk>/', management.add_staff_work_experience,name='add_staff_work_experience'),
    path('remove_wrk_exp/<str:pk>/', management.remove_wrk_exp,name='remove_wrk_exp'),
    path('add_staff_emmergency_contact/<str:pk>/', management.add_staff_emmergency_contact,name='add_staff_emmergency_contact'),
    path('remove_emm_con/<str:pk>/', management.remove_emm_con,name='remove_emm_con'),
    path('staff_profile/<str:pk>/',management.staff_profile, name='staff_profile'),
    path('manage_staff', management.manage_staff, name='manage_staff'),
    path('remove_staff/<str:pk>/',management.remove_staff, name='remove_staff'),

    path('edit_staff_edu/<str:pk>/',management.edit_staff_education, name='edit_staff_edu'),
    path('edit_staff_contact/<str:pk>/',management.edit_staff_emmergency, name='edit_staff_contact'),
    path('edit_staff_work/<str:pk>/',management.edit_staff_work, name='edit_staff_work'),

    path('delete_staff_education/<str:pk>/',management.delete_staff_education, name='delete_staff_education'),
    path('delete_staff_emmergency/<str:pk>/',management.delete_staff_emmergency, name='delete_staff_emmergency'),
    path('delete_staff_work/<str:pk>/',management.delete_staff_work, name='delete_staff_work'),

    path('add_profile_staff_education/<str:pk>/',management.add_profile_staff_education, name='add_profile_staff_education'),
    path('add_profile_staff_emmergency/<str:pk>/',
         management.add_profile_staff_emmergency, name='add_profile_staff_emmergency'),
    path('add_profile_staff_work/<str:pk>/',
         management.add_profile_staff_work, name='add_profile_staff_work'),
    path('edit_staff/<str:pk>/', management.edit_staff, name='edit_staff'),

    path('assign_staff_class/<str:pk>/',assign_classes.assign_staff_class,name='assign_staff_class'),
    path('run_stfclass',assign_classes.run_stfclass,name='run_stfclass'),

    # Parents
    path('add_parent', management.add_parent, name='add_parent'),
    path('manage_parent', management.manage_parent, name='manage_parent'),
    path('manage_student', management.manage_student, name='manage_student'),
    path('edit_parent/<str:pk>/', management.edit_parent, name='edit_parent'),
    path('delete_parent/<str:pk>/', management.delete_parent, name='delete_parent'),

    # Academic Year and Term
    path('add_academicyear', academic_year.add_academicyear, name='add_academicyear'),
    path('manage_academicyear', academic_year.manage_academicyear,name='manage_academicyear'),
    path('edit_academicyear/<str:pk>/',academic_year.edit_academicyear, name='edit_academicyear'),
    path('delete_academic_year/<str:pk>/',academic_year.delete_academic_year, name='delete_academic_year'),
    path('manage_academicterm', academic_year.manage_academicterm, name='manage_academicterm'),


    path('add_class', management.add_class, name='add_class'),
    path('manage_class', management.manage_class, name='manage_class'),
    path('edit_class/<str:pk>/',management.edit_class, name='edit_class'),
    path('delete_class/<str:pk>/', management.delete_class, name='delete_class'),

    path('add_subject/<str:pk>/', management.add_subject, name='add_subject'),
    path('edit_subject/<str:pk>/', management.edit_subject, name='edit_subject'),
    path('delete_subject/<str:pk>/',management.delete_subject, name='delete_subject'),
    path('manage_subject', management.manage_subject, name='manage_subject'),


    #attendance
    path('list_active_academic_terms',attendance.list_active_academic_terms,name='list_active_academic_terms'),
    path('select_attendance_class/<str:pk>/',attendance.select_attendance_class,name='select_attendance_class'),
    path('create_attendance/<str:pk>/<str:accadermic_terms_id>/',attendance.create_attendance,name='create_attendance'),
    path('manage_attendance', attendance.manage_attendance, name='manage_attendance'),
    path('delete_attendance/<str:pk>/',attendance.delete_attendance, name='delete_attendance'),
    path('take_attendance/<str:pk>/',attendance.take_attendance, name='take_attendance'),
    path('present/<str:pk>/<str:attendance_id>/',attendance.present, name='present'),
    path('absent/<str:pk>/<str:attendance_id>/', attendance.absent, name='absent'),
    path('view_attendance/<str:pk>/',attendance.view_attendance, name='view_attendance'),
    path('epresent/<str:pk>/', attendance.epresent, name='epresent'),
    path('eabsent/<str:pk>/', attendance.eabsent, name='eabsent'),
    path('attendance_report',attendance.attendance_report,name='attendance_report'),
    path('finish_attendance/<str:pk>/',attendance.finish_attendance,name='finish_attendance'),
    path('staff_attendance_report',attendance.staff_attendance_report,name='staff_attendance_report'),

    #Results
    path('create_results', staff.create_results, name='create_results'),
    path('manage_results', staff.manage_results, name='manage_results'),
    path('delete_results/<str:pk>/',staff.delete_results, name='delete_results'),
    path('edit_results/<str:pk>/',staff.edit_results, name='edit_results'),

    path('add_results/<str:pk>/', staff.add_results, name='add_results'),
    path('stud_results/<str:pk>/', staff.stud_results, name='stud_results'),
    path('subject_results/<str:pk>/',staff.subject_results, name='subject_results'),
    path('create_student_results/<str:pk>/',staff.create_student_results, name='create_student_results'),
    path('resultclose', staff.resultclose, name='resultclose'),
    path('view_student_result/<str:pk>/',staff.view_student_result, name='view_student_result'),
    path('print_student_result/<str:pk>/',
         staff.print_student_result, name='print_student_result'),
    path('add_promotion/<str:pk>/',staff.add_promotion, name='add_promotion'),


    path('create_bill', management.create_bill, name='create_bill'),
    path('manage_bill', management.manage_bill, name='manage_bill'),
    path('add_bill/<str:pk>/',management.add_bill, name='add_bill'),

school_management_system/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from school_management_system import settings
from django.conf.urls.static import static
from school import views
from bankapi import verify_student
from django.contrib.auth.decorators import login_required

from rest_framework import permissions
from drf_yasg.views import get_schema_view
# from rest_framework.schemas import get_schema_view
from drf_yasg import openapi
from django.views.generic import TemplateView

schema_view = get_schema_view(
    openapi.Info(
        title="MSAC API",
        default_version='v1',
        description="Welcome Mulan",
        terms_of_service="http://www.msac.edu.gh/about/",
        contact=openapi.Contact(email="terkpeh1990@gmail.com"),
        license=openapi.License(name="#"),
    ),
    public=False,
    permission_classes=(permissions.IsAuthenticated,),
)




urlpatterns = [
    # path('openapi', get_schema_view(
    #         title="Your Project",
    #         description="API for all things …",
    #         version="1.0.0"
    #     ), name='openapi-schema'),
    # path('swagger-ui/', TemplateView.as_view(
    #     template_name='swagger-ui.html',
    #     extra_context={'schema_url':'openapi-schema'}
    # ), name='swagger-ui'),
    re_path(r'^doc(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('doc/', schema_view.with_ui('swagger', cache_timeout=0),name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0),name='schema-redoc'),

    path('accounts/logout/', views.logout_request, name='django_registration_register'),


    path('docs',schema_view.as_view()),
    path('', views.login_view, name='log'),
    path('logouts', views.logout_request,name='logouts'),
    path('school/', include('school.urls', namespace='school')),
    path('shop/', include('bakery.urls', namespace='shop')),
    path('partytree/', include('partytree.urls', namespace='partytree')),
    path('salon/', include('salon.urls', namespace='salon')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),

    #bank Api
    path('students',verify_student.student.as_view()),
    path('payment',verify_student.payment.as_view()),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

templates/hod_template/footer.html
<footer class="main-footer">
      <strong>Copyright &copy; {% now "Y" %}, <a href="https://vijaythapa.com.np">Vijay Thapa</a>.</strong> 
      All rights reserved.
      <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 1.0
      </div>
    </footer>

templates/hod_template/manage_parent.html
{% extends "base.html" %}
{% block content%}

<div class="col-lg">
    <div class="card card-primary card-outline">
        <div class="card-body">
            <a class="btn btn-outline-primary btn-sm mb-1" href="{% url 'school:add_parent' %}">Add Parent</a>
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="example2" class="table table-bordered table-striped table-hover" role="grid"
                            aria-describedby="example2_info">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1"
                                        colspan="1" aria-sort="ascending"
                                        aria-label="Rendering engine: activate to sort column descending">ID
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Father's Name</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Platform(s): activate to sort column ascending"> Contact</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Engine version: activate to sort column ascending">Mother's Name</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Engine version: activate to sort column ascending">Contact</th>
                                   
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="CSS grade: activate to sort column ascending">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for parent in parent_list %}
                                </tr>
                                <tr role="row" class="odd">
                                    <td class="sorting_1">{{parent.id}}</td>
                                    <td>{{parent.father_name}}</td>
                                    <td>{{parent.father_phone}}</td>
                                    <td>{{parent.mother_name}}</td>
                                    <td>{{parent.mother_phone}}</td>
                                    <td>
                                      <a class="btn btn-sm btn-warning" href="{% url 'school:edit_parent' parent.id %}">Edit</a>
                                    <a class="btn btn-sm btn-danger" href="{% url 'school:delete_parent' parent.id %}">Delete</a>
                                    <a class="btn btn-sm btn-primary" href="{% url 'school:add_student' parent.id %}">Add Student</a>
                                    </td>
                                </tr>

                                {% endfor %}

                            </tbody>
                            <tfoot>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.card -->
</div>
{% endblock %}

templates/hod_template/staff_education_history.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content ">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">

                <!-- Profile Image -->
                <div class="card card-primary card-outline">
                    <div class="card-body box-profile">
                        <div class="text-center">
                            <img class="profile-user-img img-fluid img-circle" src=" {{students.profile_pic.url}}"
                                alt="User profile picture">
                        </div>

                        <h3 class="profile-username text-center">{{students.Surname }} {{ students.firstname}}</h3>
                        <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                                <b>Class</b> <a class="float-right">{{students.course_id}}</a>
                            </li>
                            <li class="list-group-item">
                                <b>Gender</b> <a class="float-right">{{students.gender}}</a>
                            </li>
                            <li class="list-group-item">
                                <b>Date of Birth</b> <a class="float-right">{{students.dob}}</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

                <!-- About Me Box -->
                <div class="card card-primary card-outline">

                    <!-- /.card-header -->
                    <div class="card-body">
                        
                        <strong><i class="fas fa-map-marker-alt mr-1"></i> Location</strong>

                        <p class="text-muted">{{students.residential_address}}</p>

                        <hr>
                        <strong><i class="fa fa-phone mr-1"></i> Location</strong>
                        
                        <p class="text-muted">{{students.phone}}</p>
                        

                        <!-- <strong><i class="fas fa-pencil-alt mr-1"></i> Skills</strong>
            
                        <p class="text-muted">
                            <span class="tag tag-danger">UI Design</span>
                            <span class="tag tag-success">Coding</span>
                            <span class="tag tag-info">Javascript</span>
                            <span class="tag tag-warning">PHP</span>
                            <span class="tag tag-primary">Node.js</span>
                        </p>
            
                        <hr> -->

                        <!-- <strong><i class="far fa-file-alt mr-1"></i> Notes</strong>
            
                        <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.
                        </p> -->
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>

            <div class="col-9 novalidate">

                <div class="row">
                    <div class="col-lg">
                        <div class="card ">
                            <div class="card-header bg-primary color-palette">
                                <h3 class="card-title">Education History</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form role="form" method="POST" enctype="multipart/form-data" novalidate>
                                {% csrf_token %}
                                <div class="card-body">
                                    <div class="row">
                                        <div class="form-group col">
                                            {{ form.schname|as_crispy_field }}
                                        </div>
                                        <div class="form-group col">
                                            {{ form.qualification|as_crispy_field }}
                                        </div>
                                       
                                    </div>
                                    <div class="row">
                                        <div class="form-group col">
                                            {{ form.startdate|as_crispy_field }}
                                        </div>
                                        <div class="form-group col">
                                            {{ form.enddate|as_crispy_field }}
                                        </div>
                                       
                                    </div>
                                    <div class="row">
                                        <div class="form-group col">
                                            <button type="submit" class="btn btn-md btn-outline-primary">Submit</button>
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        
                                        <div class="form-group col float-left">
                                            
                                            <a class="btn btn-md btn-outline-warning"href="{% url 'school:add_staff_work_experience' students.id %}"><i class="fas fa-arrow-right"></i></a>
                                        </div>
                                       
                                    </div>
                                </div>


                            </form>
                            
                            <br>
                            {% if staff_edu %}
                                    <div class="m-4">
                                        <div id="example3_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <table id="example3" class="table  table-striped table-hover" role="grid"
                                                        aria-describedby="example2_info">
                                                        <thead class="">
                                                            <tr role="row">
                            
                                                                
                                                                
                                                                
                                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                                                    aria-label="Browser: activate to sort column ascending">School</th>
                                                                
                                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                                                    aria-label="Browser: activate to sort column ascending">Duration</th>
                                                                
                                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                                                    aria-label="Browser: activate to sort column ascending">Qualification</th>
                                                                
                                    
                                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                                                    aria-label="CSS grade: activate to sort column ascending">Action</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            {% for a in staff_edu %}
                                                            </tr>
                                                            <tr role="row" class="odd">
                                                                
                                                                
                                                                <td>{{ a.schname}}</td>
                                                                <td>{{ a.startdate }}  to {{ a.enddate}}</td>
                                                                <td>{{a.qualification}}</td>
                                                              
                                                            
                                                                <td>
                                                                    
                                                                
                                                                    <a class="btn btn-sm btn-outline-danger mr-2 mb-1"
                                                                        href="{% url 'school:remove_edu_history' a.id %}">Delete</a>
                                                                    
                                                                   
                                                                </td>
                                                            </tr>
                            
                                                            {% endfor %}
                            
                                                        </tbody>
                            
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% else %}
                                    <div class="m-4">
                                        <div class="jumbotron">
                                            <div class="col-md-10 mx-auto">
                                              <p class="d-flex justify-content-center"><b>No Education Information</b></p>
                                            </div>
                                        </div> 
                                    </div>
                                    
                                        
                            {% endif %}
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
</div>


</div>



{% endblock %}